[tool.poetry]
name = "ta-ml-model-api"
version = "0.1.0"
description = ""
authors = ["Renato Ramos <renatoramossilva@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
